# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Anaekran(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(522, 412)
        self.Anaekran = QtWidgets.QPushButton(Form)
        self.Anaekran.setGeometry(QtCore.QRect(60, 160, 93, 28))
        self.Anaekran.setObjectName("Anaekran")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(320, 160, 81, 21))
        self.label.setMouseTracking(False)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Anaekran.setText(_translate("Form", "A Button"))
        self.label.setText(_translate("Form", "TextLabel"))

class Anaekran(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Anaekran()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
